import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { serveMaizzle } from '../test/maizzle-serve';

const fixture = fileURLToPath(new URL('../test/fixture', import.meta.url));
const cases = fileURLToPath(new URL('../test/.cases', import.meta.url));
const maizzle = fileURLToPath(
	new URL('../node_modules/.bin/maizzle', import.meta.url),
);

/** Runs `maizzle <args>` in `cwd`, as a project runs it. */
async function run(cwd: string, ...args: string[]) {
	const child = Bun.spawn([maizzle, ...args], {
		cwd,
		stdout: 'pipe',
		stderr: 'pipe',
	});
	const [code, stdout, stderr] = await Promise.all([
		child.exited,
		new Response(child.stdout).text(),
		new Response(child.stderr).text(),
	]);
	return { code, output: stdout + stderr };
}

async function build(cwd: string, ...args: string[]): Promise<void> {
	const { code, output } = await run(cwd, 'build', ...args);
	if (code !== 0) throw new Error(`maizzle build failed:\n${output}`);
}

const read = (path: string) => Bun.file(`${fixture}/${path}`).text();

describe('a project built with the i18n plugin', () => {
	/** Whether generated/mail.ts was there before the default build: the flat one writes none. */
	let typesBeforeDefault = true;

	beforeAll(async () => {
		for (const dir of [
			'dist',
			'dist-flat',
			'dist-parallel',
			'.maizzle',
			'generated',
		]) {
			rmSync(`${fixture}/${dir}`, { recursive: true, force: true });
		}
		await build(fixture, '-c', 'maizzle.config.flat.ts');
		await build(fixture, '-c', 'maizzle.config.parallel.ts');
		typesBeforeDefault = await Bun.file(
			`${fixture}/generated/mail.ts`,
		).exists();
		await build(fixture);
	}, 120_000);

	test("types the renderer with the build's e-mails, a URL variable as a string", async () => {
		expect(await read('generated/mail.ts')).toBe(
			[
				'// Generated by @nxgt/mail-i18n from the build, after each maizzle build.',
				'// Never edited, never committed: git-ignore it, and build before type-checking.',
				'',
				'/** The e-mails of the build, each with the variables it takes when it is sent. */',
				'export interface MailEmails {',
				'\t"auth/reset-password": { readonly email: string | number; readonly resetLink: string };',
				'\t"verify-email": { readonly link: string; readonly name: string | number };',
				'}',
				'',
			].join('\n'),
		);
		// Where rendererTypes says, a parallel build's too, and nowhere with false.
		expect(await read('generated/parallel/mail.ts')).toBe(
			await read('generated/mail.ts'),
		);
		expect(typesBeforeDefault).toBe(false);
	});

	test('writes every template in every locale, with its text part', async () => {
		for (const locale of ['en', 'fr']) {
			for (const email of ['verify-email', 'auth/reset-password']) {
				expect(
					await Bun.file(`${fixture}/dist/${locale}/${email}.html`).exists(),
				).toBe(true);
				expect(
					await Bun.file(`${fixture}/dist/${locale}/${email}.txt`).exists(),
				).toBe(true);
			}
		}
	});

	test('formats each locale with its own plural and date', async () => {
		const en = await read('dist/en/verify-email.html');
		const fr = await read('dist/fr/verify-email.html');
		expect(en).toContain('<html lang="en" dir="ltr"');
		expect(en).toContain('<h1>Confirm your e-mail address</h1>');
		expect(en).toContain('The link expires in 15 minutes.');
		expect(en).toContain('Sent on January 2, 2026.');
		expect(fr).toContain('<html lang="fr" dir="ltr"');
		expect(fr).toContain('Le lien expire dans 15 minutes.');
		expect(fr).toContain('Envoyé le 2 janvier 2026.');
	});

	test('keeps each placeholder for the renderer, in text and in a link', async () => {
		const fr = await read('dist/fr/verify-email.html');
		expect(fr).toContain('<p>Bonjour {{ name }},</p>');
		expect(fr).toContain('<a href="{{ link }}">');
		expect(await read('dist/fr/verify-email.txt')).toContain('{{ link }}');
	});

	test('writes the manifest the renderer reads', async () => {
		expect(JSON.parse(await read('dist/mail-manifest.json'))).toEqual(
			JSON.parse(await read('mail-manifest.golden.json')),
		);
	});

	test('writes the types of t for the editor, in .maizzle/ where the starter looks', async () => {
		const types = await read('.maizzle/nxgt-mail-i18n.d.ts');
		expect(types).toContain("'verify-email.expires': { minutes: number };");
		expect(types).toContain("'verify-email.title': { };");
	});

	test('a parallel build writes the same manifest: the workers write no wrapper', async () => {
		expect(JSON.parse(await read('dist-parallel/mail-manifest.json'))).toEqual(
			JSON.parse(await read('mail-manifest.golden.json')),
		);
		expect(await read('dist-parallel/fr/verify-email.html')).toContain(
			'Envoyé le 2 janvier 2026.',
		);
	});

	test('the flat layout writes each locale next to the others', async () => {
		expect(await read('dist-flat/verify-email.fr.html')).toContain(
			'Le lien expire dans 15 minutes.',
		);
		const manifest = JSON.parse(await read('dist-flat/mail-manifest.json'));
		expect(manifest.emails['auth/reset-password'].files.fr).toEqual({
			html: 'auth/reset-password.fr.html',
			text: 'auth/reset-password.fr.txt',
		});
	});

	test('maizzle serve lists every template in every locale', async () => {
		const server = await serveMaizzle(maizzle, fixture);
		try {
			const list: { path: string }[] = await fetch(
				`${server.origin}/__maizzle/templates`,
			).then((response) => response.json());
			expect(list.map((template) => template.path).sort()).toEqual([
				'.maizzle/emails/en/auth/reset-password.vue',
				'.maizzle/emails/en/verify-email.vue',
				'.maizzle/emails/fr/auth/reset-password.vue',
				'.maizzle/emails/fr/verify-email.vue',
			]);
			const fr = await fetch(
				`${server.origin}/__maizzle/render/.maizzle/emails/fr/verify-email`,
			).then((response) => response.text());
			expect(fr).toContain('Bonjour {{ name }},');
		} finally {
			await server.stop();
		}
	}, 120_000);
});

const en = {
	'verify-email': {
		subject: 'Confirm your address, {name}',
		title: 'Confirm your address',
		expires: 'In {minutes, plural, one {# minute} other {# minutes}}.',
	},
};
const fr = {
	'verify-email': {
		subject: 'Confirmez votre adresse, {name}',
		title: 'Confirmez votre adresse',
		expires: 'Dans {minutes, plural, one {# minute} other {# minutes}}.',
	},
};

/** Writes a project under test/.cases/<name>, builds it, and answers what the build printed. */
async function failure(
	name: string,
	files: Record<string, string | object | null>,
): Promise<string> {
	const root = `${cases}/${name}`;
	rmSync(root, { recursive: true, force: true });
	const all: Record<string, string | object | null> = {
		'maizzle.config.ts': [
			"import { defineMailConfig } from '@nxgt/mail-config';",
			"import { i18n } from '../../../src/index';",
			"export default defineMailConfig({ plugins: [i18n({ locales: ['en', 'fr'] })] });",
		].join('\n'),
		'locales/en.json': en,
		'locales/fr.json': fr,
		'emails/verify-email.vue':
			"<template><p>{{ t('verify-email.title') }}</p></template>",
		...files,
	};
	for (const [path, content] of Object.entries(all)) {
		if (content === null) continue;
		mkdirSync(dirname(`${root}/${path}`), { recursive: true });
		writeFileSync(
			`${root}/${path}`,
			typeof content === 'string' ? content : JSON.stringify(content),
		);
	}
	const { code, output } = await run(root, 'build');
	expect(code).not.toBe(0);
	return output;
}

describe('a build failure names the locale, the template and the key', () => {
	afterAll(() => rmSync(cases, { recursive: true, force: true }));

	const template = (body: string) => ({
		'emails/verify-email.vue': `<template><p>${body}</p></template>`,
	});

	test.each([
		[
			'unknown-key',
			template("{{ t('verify-email.titel') }}"),
			"i18n: <locale>: verify-email calls t('verify-email.titel'), which is not a key of the catalogues",
		],
		[
			'missing-argument',
			template("{{ t('verify-email.expires') }}"),
			"i18n: <locale>: verify-email calls t('verify-email.expires') without {minutes}",
		],
		[
			'placeholder-as-number',
			template(
				"{{ t('verify-email.expires', { minutes: placeholder('minutes') }) }}",
			),
			'i18n: <locale>: verify-email passes {minutes} to verify-email.expires as a string — the message uses it as a number',
		],
		[
			'unused-argument',
			template("{{ t('verify-email.title', { name: 'Ada' }) }}"),
			'i18n: <locale>: verify-email passes {name} to verify-email.title, which does not use it',
		],
		[
			'placeholder-name',
			template("{{ placeholder('first name') }}"),
			"i18n: <locale>: verify-email calls placeholder() with a name that is not camelCase — as placeholder('firstName')",
		],
		[
			'no-subject',
			{ 'emails/welcome.vue': '<template><p>hi</p></template>' },
			'i18n: welcome has no subject — add welcome.subject to the catalogues',
		],
		[
			'template-name',
			{ 'emails/Welcome.vue': '<template><p>hi</p></template>' },
			'i18n: emails/Welcome.vue is not a kebab-case name — name a template as verify-email.vue',
		],
		[
			'content-set-by-the-project',
			{
				'maizzle.config.ts': [
					"import { defineMailConfig } from '@nxgt/mail-config';",
					"import { i18n } from '../../../src/index';",
					"export default defineMailConfig({ plugins: [i18n({ locales: ['en', 'fr'] })], content: ['emails/**/*.vue'] });",
				].join('\n'),
			},
			'i18n: emails/verify-email.vue is not built through the i18n plugin — leave content to it, and put templates in emails/',
		],
		[
			'subject-number',
			{
				'locales/en.json': {
					'verify-email': {
						...en['verify-email'],
						subject: '{n, number} to confirm',
					},
				},
				'locales/fr.json': {
					'verify-email': {
						...fr['verify-email'],
						subject: '{n, number} à confirmer',
					},
				},
			},
			"i18n: <locale>: verify-email.subject uses {n} as a number — a subject's arguments are placeholders, filled at send time as strings",
		],
		[
			'arguments-not-an-object',
			template("{{ t('verify-email.title', null) }}"),
			"i18n: <locale>: verify-email calls t('verify-email.title') with arguments that are not an object, as { name: placeholder('name') }",
		],
		[
			'placeholder-to-select',
			{
				'locales/en.json': {
					'verify-email': {
						...en['verify-email'],
						title: '{plan, select, pro {Pro} other {Free}}',
					},
				},
				'locales/fr.json': {
					'verify-email': {
						...fr['verify-email'],
						title: '{plan, select, pro {Pro} other {Gratuit}}',
					},
				},
				'emails/verify-email.vue':
					"<template><p>{{ t('verify-email.title', { plan: placeholder('plan') }) }}</p></template>",
			},
			'i18n: <locale>: verify-email passes a placeholder to {plan}, which verify-email.title chooses on with a select — a placeholder always chooses other',
		],
		[
			'no-catalogue',
			{ 'locales/fr.json': null },
			'i18n: locales/fr.json is missing — every locale has a catalogue',
		],
		[
			'broken-catalogue',
			{ 'locales/fr.json': '' },
			'i18n: locales/fr.json is not valid JSON',
		],
		[
			'missing-key',
			{
				'locales/fr.json': {
					'verify-email': { ...fr['verify-email'], title: undefined },
				},
			},
			'i18n: fr: verify-email.title is missing — en, the fallback locale, has it',
		],
	])(
		'%s',
		async (name, files, message) => {
			// Maizzle builds the locales in no set order: either may fail first.
			const pattern = message
				.split('<locale>')
				.map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
				.join('(en|fr)');
			expect(await failure(name, files)).toMatch(new RegExp(pattern));
		},
		60_000,
	);
});

describe('a right-to-left locale', () => {
	const root = `${cases}/rtl`;
	afterAll(() => rmSync(root, { recursive: true, force: true }));

	beforeAll(async () => {
		rmSync(root, { recursive: true, force: true });
		// A small catalogue for this fixture alone: mail-i18n's shared messages
		// ship en/fr only (see docs/guide/right-to-left.md), so a project adding
		// ar writes its own catalogue, as this test does.
		const files: Record<string, string | object> = {
			'maizzle.config.ts': [
				"import { defineMailConfig } from '@nxgt/mail-config';",
				"import { i18n } from '../../../src/index';",
				"export default defineMailConfig({ plugins: [i18n({ locales: ['en', 'ar'] })] });",
			].join('\n'),
			'locales/en.json': {
				'verify-email': { subject: 'Confirm', title: 'Confirm your address' },
			},
			'locales/ar.json': {
				'verify-email': { subject: 'تأكيد', title: 'تأكيد عنوانك' },
			},
			'emails/verify-email.vue': [
				'<template>',
				'  <Html :lang="locale" :dir="dir">',
				'    <Body>',
				"      <Container><Text>{{ t('verify-email.title') }}</Text></Container>",
				'    </Body>',
				'  </Html>',
				'</template>',
			].join('\n'),
		};
		for (const [path, content] of Object.entries(files)) {
			mkdirSync(dirname(`${root}/${path}`), { recursive: true });
			writeFileSync(
				`${root}/${path}`,
				typeof content === 'string' ? content : JSON.stringify(content),
			);
		}
		await build(root);
	}, 60_000);

	test('gets dir="rtl" beside its locale, an ltr locale keeps dir="ltr"', async () => {
		const ar = await Bun.file(`${root}/dist/ar/verify-email.html`).text();
		const en = await Bun.file(`${root}/dist/en/verify-email.html`).text();
		expect(ar).toContain('dir="rtl"');
		expect(ar).toContain('تأكيد عنوانك');
		expect(en).toContain('dir="ltr"');
	});
});
