import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { ArgumentKind, Messages } from './catalogues';
import type { Manifest } from './manifest';

/** Where the template types go, under the project: `.maizzle/*.d.ts` is in the starter's `tsconfig.json`. */
export const TYPES_FILE = '.maizzle/nxgt-mail-i18n.d.ts';

/** What `t` accepts for each kind — as the build checks it. */
const TYPE_OF: Readonly<Record<ArgumentKind, string>> = {
	string: 'string | number',
	number: 'number',
	date: 'Date | number',
};

/**
 * The declaration file that types `t` in the templates: each key of the
 * `reference` catalogue, with its arguments, so an editor completes a key and
 * flags an unknown one or a missing argument. Keys and names are checked
 * before this runs, so they are safe to write quoted.
 */
export function templateTypes(
	reference: Messages,
	fallbackLocale: string,
): string {
	const entries = [...reference.entries()]
		.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
		.map(([key, message]) => {
			const args = [...message.args.entries()]
				.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
				.map(([name, kind]) => `${name}: ${TYPE_OF[kind]}`);
			return `\t\t'${key}': { ${args.join('; ')}${args.length > 0 ? ' ' : ''}};`;
		});
	return [
		`// Generated by @nxgt/mail-i18n from the ${fallbackLocale} catalogue, each time the config loads.`,
		'// Never edited, never committed: it types t() in the templates.',
		"import type {} from '@nxgt/mail-i18n';",
		'',
		"declare module '@nxgt/mail-i18n' {",
		'\tinterface TemplateMessages {',
		...entries,
		'\t}',
		'}',
		'',
	].join('\n');
}

/** The first line of the renderer's types: a file without it is not the plugin's to replace. */
const RENDERER_TYPES_HEADER = '// Generated by @nxgt/mail-i18n from the build';

/** Where the renderer's types go, under the project, by default. */
export const RENDERER_TYPES_FILE = 'generated/mail.ts';

/**
 * The module that types the renderer: `MailEmails`, each e-mail of the build
 * with the variables it takes at send time, for
 * `createMailRenderer<MailEmails>(…)`. A URL variable takes a string; any
 * other a string or a number, as `render` writes it. `@nxgt/mail`'s
 * `RenderArguments` reads `Readonly<Record<string, never>>` as an e-mail
 * without variables, and its type specs copy this output: change them
 * together.
 */
export function rendererTypes(manifest: Manifest): string {
	const entries = Object.entries(manifest.emails)
		.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
		.map(([email, { variables, urlVariables }]) => {
			const fields = variables.map(
				(name) =>
					`readonly ${name}: ${urlVariables.includes(name) ? 'string' : 'string | number'}`,
			);
			const type =
				fields.length > 0
					? `{ ${fields.join('; ')} }`
					: 'Readonly<Record<string, never>>';
			// A name is a file's path, quoted as JSON: valid TypeScript whatever it holds.
			return `\t${JSON.stringify(email)}: ${type};`;
		});
	return [
		`${RENDERER_TYPES_HEADER}, after each maizzle build.`,
		'// Never edited, never committed: git-ignore it, and build before type-checking.',
		'',
		'/** The e-mails of the build, each with the variables it takes when it is sent. */',
		'export interface MailEmails {',
		...entries,
		'}',
		'',
	].join('\n');
}

/**
 * Writes the renderer's types to `file`, shown as `path` — unless `file` holds
 * something the plugin did not write: that **throws**, and the file is kept.
 */
export function writeRendererTypes(
	file: string,
	path: string,
	source: string,
): void {
	if (
		existsSync(file) &&
		!readFileSync(file, 'utf8').startsWith(RENDERER_TYPES_HEADER)
	) {
		throw new Error(
			`i18n: ${path} was not written by i18n() — point rendererTypes at a file of its own`,
		);
	}
	writeIfChanged(file, source);
}

/** Writes `source` to `file` only when it changed, so an editor or a watcher sees a change only where there is one. */
export function writeIfChanged(file: string, source: string): void {
	if (existsSync(file) && readFileSync(file, 'utf8') === source) return;
	mkdirSync(dirname(file), { recursive: true });
	writeFileSync(file, source);
}
