import { afterEach, describe, expect, test } from 'bun:test';
import {
	mkdtempSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { checkCatalogues } from './catalogues';
import {
	rendererTypes,
	templateTypes,
	writeIfChanged,
	writeRendererTypes,
} from './types';

const reference = checkCatalogues(
	{
		en: {
			welcome: {
				title: 'Welcome',
				body: 'Hello {name}, {count, plural, one {# seat} other {# seats}} since {at, date}.',
			},
		},
	},
	['en'],
	'en',
).get('en');

describe('templateTypes', () => {
	test('declares every key of the reference catalogue, sorted, with its arguments', () => {
		expect(templateTypes(reference as never, 'en')).toBe(
			[
				'// Generated by @nxgt/mail-i18n from the en catalogue, each time the config loads.',
				'// Never edited, never committed: it types t() in the templates.',
				"import type {} from '@nxgt/mail-i18n';",
				'',
				"declare module '@nxgt/mail-i18n' {",
				'\tinterface TemplateMessages {',
				"\t\t'welcome.body': { at: Date | number; count: number; name: string | number };",
				"\t\t'welcome.title': { };",
				'\t}',
				'}',
				'',
			].join('\n'),
		);
	});
});

describe('rendererTypes', () => {
	const email = (variables: string[], urlVariables: string[] = []) => ({
		variables,
		urlVariables,
		subject: {},
		files: {},
	});

	test('types each e-mail, sorted, with its variables, none as an empty record', () => {
		expect(
			rendererTypes({
				locales: ['en'],
				fallbackLocale: 'en',
				emails: {
					welcome: email([]),
					"it's/verify": email(['link', 'name'], ['link']),
				},
			}),
		).toBe(
			[
				'// Generated by @nxgt/mail-i18n from the build, after each maizzle build.',
				'// Never edited, never committed: git-ignore it, and build before type-checking.',
				'',
				'/** The e-mails of the build, each with the variables it takes when it is sent. */',
				'export interface MailEmails {',
				'\t"it\'s/verify": { readonly link: string; readonly name: string | number };',
				'\t"welcome": Readonly<Record<string, never>>;',
				'}',
				'',
			].join('\n'),
		);
	});
});

describe('writeIfChanged', () => {
	let dir = '';
	afterEach(() => rmSync(dir, { recursive: true, force: true }));

	test('writes a file, its folder too, and leaves it alone when unchanged', async () => {
		dir = mkdtempSync(join(tmpdir(), 'mail-i18n-types-'));
		const file = join(dir, '.maizzle/types.d.ts');
		writeIfChanged(file, 'a');
		const first = statSync(file).mtimeMs;
		await Bun.sleep(20);
		writeIfChanged(file, 'a');
		expect(statSync(file).mtimeMs).toBe(first);
		writeIfChanged(file, 'b');
		expect(readFileSync(file, 'utf8')).toBe('b');
	});
});

describe('writeRendererTypes', () => {
	let dir = '';
	afterEach(() => rmSync(dir, { recursive: true, force: true }));

	test('writes a new file and replaces its own, but never a file it did not write', () => {
		dir = mkdtempSync(join(tmpdir(), 'renderer-types-'));
		const file = join(dir, 'generated/mail.ts');
		const source = (body: string) =>
			`// Generated by @nxgt/mail-i18n from the build, after each maizzle build.\n${body}`;
		writeRendererTypes(file, 'generated/mail.ts', source('a'));
		writeRendererTypes(file, 'generated/mail.ts', source('b'));
		expect(readFileSync(file, 'utf8')).toBe(source('b'));
		const own = join(dir, 'index.ts');
		writeFileSync(own, 'export const app = 1;\n');
		expect(() => writeRendererTypes(own, 'index.ts', source('c'))).toThrow(
			new Error(
				'i18n: index.ts was not written by i18n() — point rendererTypes at a file of its own',
			),
		);
		expect(readFileSync(own, 'utf8')).toBe('export const app = 1;\n');
	});
});
