import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { ArgumentKind, Messages } from './catalogues';

/** Where the template types go, under the project: `.maizzle/*.d.ts` is in the starter's `tsconfig.json`. */
export const TYPES_FILE = '.maizzle/nxgt-mail-i18n.d.ts';

/** What `t` accepts for each kind — as the build checks it. */
const TYPE_OF: Readonly<Record<ArgumentKind, string>> = {
	string: 'string | number',
	number: 'number',
	date: 'Date | number',
};

/**
 * The declaration file that types `t` in the templates: each key of the
 * `reference` catalogue, with its arguments, so an editor completes a key and
 * flags an unknown one or a missing argument. Keys and names are checked
 * before this runs, so they are safe to write quoted.
 */
export function templateTypes(
	reference: Messages,
	fallbackLocale: string,
): string {
	const entries = [...reference.entries()]
		.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
		.map(([key, message]) => {
			const args = [...message.args.entries()]
				.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
				.map(([name, kind]) => `${name}: ${TYPE_OF[kind]}`);
			return `\t\t'${key}': { ${args.join('; ')}${args.length > 0 ? ' ' : ''}};`;
		});
	return [
		`// Generated by @nxgt/mail-i18n from the ${fallbackLocale} catalogue, each time the config loads.`,
		'// Never edited, never committed: it types t() in the templates.',
		"import type {} from '@nxgt/mail-i18n';",
		'',
		"declare module '@nxgt/mail-i18n' {",
		'\tinterface TemplateMessages {',
		...entries,
		'\t}',
		'}',
		'',
	].join('\n');
}

/** Writes `source` to `file` only when it changed, so an editor or a watcher sees a change only where there is one. */
export function writeIfChanged(file: string, source: string): void {
	if (existsSync(file) && readFileSync(file, 'utf8') === source) return;
	mkdirSync(dirname(file), { recursive: true });
	writeFileSync(file, source);
}
