import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';

/**
 * Where each locale's output goes: `nested` writes `en/verify-email.html`,
 * `flat` writes `verify-email.en.html`.
 */
export type Layout = 'nested' | 'flat';

/** One e-mail in one locale: `{ email: 'auth/reset-password', locale: 'fr' }`. */
export interface Entry {
	readonly email: string;
	readonly locale: string;
}

const NAME = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

const posix = (path: string) => path.split(sep).join('/');

/** Every `.vue` file under `dir`, as a slash-separated path without `.vue`. */
function listEmails(dir: string, label: string): string[] {
	if (!existsSync(dir)) return [];
	return readdirSync(dir, { recursive: true, encoding: 'utf8' })
		.filter((file) => file.endsWith('.vue'))
		.map((file) => {
			const email = posix(file).slice(0, -'.vue'.length);
			for (const segment of email.split('/')) {
				if (!NAME.test(segment)) {
					throw new Error(
						`i18n: ${label}/${email}.vue is not a kebab-case name — name a template as verify-email.vue`,
					);
				}
			}
			return email;
		})
		.sort();
}

/** The path of `entry`'s file under a folder laid out as `layout`, without an extension. */
export function entryPath(entry: Entry, layout: Layout): string {
	return layout === 'nested'
		? `${entry.locale}/${entry.email}`
		: `${entry.email}.${entry.locale}`;
}

/**
 * Reads back what {@link entryPath} wrote — `path` relative to its folder,
 * slash-separated, without an extension — or `null` for a path that is not
 * one e-mail in one of `locales`.
 */
export function parseEntry(
	path: string,
	layout: Layout,
	locales: readonly string[],
): Entry | null {
	if (layout === 'nested') {
		const [locale, ...rest] = path.split('/');
		if (locale === undefined || rest.length === 0) return null;
		return locales.includes(locale) ? { email: rest.join('/'), locale } : null;
	}
	const dot = path.lastIndexOf('.');
	const locale = path.slice(dot + 1);
	return dot > 0 && locales.includes(locale)
		? { email: path.slice(0, dot), locale }
		: null;
}

function wrapperSource(wrapper: string, template: string): string {
	const from = posix(relative(dirname(wrapper), template));
	return [
		'<!-- Generated by @nxgt/mail-i18n: one per template and locale. Never edited, never committed. -->',
		'<script setup>',
		`import Email from '${from.startsWith('.') ? from : `./${from}`}';`,
		'</script>',
		'<template><Email /></template>',
		'',
	].join('\n');
}

/** Every file under `dir`, absolute. */
function listFiles(dir: string): string[] {
	if (!existsSync(dir)) return [];
	return readdirSync(dir, { recursive: true, encoding: 'utf8' })
		.map((file) => join(dir, file))
		.filter((file) => file.endsWith('.vue'));
}

/**
 * A folder of templates. `label` names it in an error: `emails`, or
 * `templates[0]` for a package's. `only`, when given, keeps those e-mails of
 * the folder and no other. A `packaged` folder — a package's — must hold
 * templates, and shares no name with another package's.
 */
export interface TemplateFolder {
	readonly dir: string;
	readonly label: string;
	readonly only?: readonly string[];
	readonly packaged?: boolean;
}

/** The e-mails of `folder`, the ones it keeps, checked. */
function folderEmails({
	dir,
	label,
	only,
	packaged,
}: TemplateFolder): string[] {
	const emails = listEmails(dir, label);
	if (packaged && emails.length === 0) {
		throw new Error(
			`i18n: ${label} holds no template — is ${dir} the folder of a package's e-mails?`,
		);
	}
	for (const email of only ?? []) {
		if (!emails.includes(email)) {
			throw new Error(
				`i18n: ${label} has no template ${email}.vue — name one of its e-mails`,
			);
		}
	}
	return [...(only ?? emails)];
}

/**
 * Each e-mail of `folders` and its file. The project's folder, first, wins
 * over a package's; two packages with the same e-mail **throw**, since
 * neither would be the obvious one.
 */
function collectTemplates(
	folders: readonly TemplateFolder[],
): Map<string, string> {
	const templates = new Map<string, string>();
	const owners = new Map<string, TemplateFolder>();
	for (const folder of folders) {
		for (const email of folderEmails(folder)) {
			const owner = owners.get(email);
			if (owner === undefined) {
				owners.set(email, folder);
				templates.set(email, join(folder.dir, `${email}.vue`));
			} else if (owner.packaged) {
				throw new Error(
					`i18n: ${owner.label} and ${folder.label} both have ${email}.vue — keep one with emails: [...], or write the project's own in its folder`,
				);
			}
		}
	}
	return templates;
}

/**
 * Writes one wrapper per template of `folders` and locale under
 * `wrappersDir` — the project's folder first, so its template replaces a
 * package's of the same name — each only when its text changed, and removes
 * the wrappers of templates that are gone, so a running dev server sees a
 * change only where there is one. Answers the e-mails, sorted.
 */
export function writeWrappers(options: {
	readonly folders: readonly TemplateFolder[];
	readonly wrappersDir: string;
	readonly locales: readonly string[];
	readonly layout: Layout;
}): string[] {
	const { wrappersDir, locales, layout } = options;
	const templates = collectTemplates(options.folders);
	const wanted = new Set<string>();
	for (const [email, template] of templates) {
		for (const locale of locales) {
			const wrapper = join(
				wrappersDir,
				`${entryPath({ email, locale }, layout)}.vue`,
			);
			wanted.add(wrapper);
			const source = wrapperSource(wrapper, template);
			if (existsSync(wrapper) && readFileSync(wrapper, 'utf8') === source) {
				continue;
			}
			mkdirSync(dirname(wrapper), { recursive: true });
			writeFileSync(wrapper, source);
		}
	}
	for (const file of listFiles(wrappersDir)) {
		if (!wanted.has(file)) rmSync(file);
	}
	return [...templates.keys()].sort();
}

/** The part of Vite's dev server the watcher uses. */
interface WatchedServer {
	readonly watcher: {
		add(path: string): void;
		on(event: 'add' | 'unlink', listener: (file: string) => void): void;
	};
}

/**
 * A Vite plugin for Maizzle's renderer: under `maizzle serve`, a template
 * added to or removed from `emailsDir` gets its wrappers at once, so the
 * preview lists it without a restart. A template the build would refuse is
 * reported, never thrown: an error in a watcher would stop the server.
 */
export function watchTemplates(emailsDir: string, regenerate: () => void) {
	return {
		name: 'nxgt-mail-i18n:wrappers',
		configureServer(server: WatchedServer) {
			server.watcher.add(emailsDir);
			const onTemplate = (file: string) => {
				if (!file.startsWith(emailsDir + sep) || !file.endsWith('.vue')) return;
				try {
					regenerate();
				} catch (error) {
					console.error(error instanceof Error ? error.message : error);
				}
			};
			server.watcher.on('add', onTemplate);
			server.watcher.on('unlink', onTemplate);
		},
	};
}
